### PR TITLE
Update to work with kRPC server v0.4.0

### PR DESCRIPTION
**Pull request by TeWu**
This PR introduces changes required to work with kRPC server v0.4.0 (as described in [kRPC pull request #325][1]) and some additional improvements.

[1]: https://github.com/krpc/krpc/pull/325

### CODE REVIEW

**Comment by nateberkopec** [comment]
Is this supposed to work on 0.3.8/9?

**Comment by TeWu** [comment]
@nateberkopec No, `proto_change_0.4` branch won't work with kRPC server v0.3.8/9.
The reason is that kRPC server v0.4.0 introduces breaking changes to the communication protocol ([see here](https://github.com/krpc/krpc/pull/325)), and `proto_change_0.4` branch introduces corresponding, **not backward compatible** changes to the client.

If you are using **kRPC server v0.3.8/9** then use **krpc-rb v0.3.1** - that is version from `master` branch that can be installed like that: `gem install krpc`.
If you are using **kRPC server v0.4.x** then use **krpc-rb v0.4.0.betaX** -  that is version from `proto_change_0.4` branch that can be installed like that: `gem install krpc --pre`.

**Comment by nateberkopec** [comment]
I'll be using this library for my RubyConf talk. Will try to get some feedback to you over the next few weeks on this beta branch.

**Comment by TeWu** [comment]
@nateberkopec That's great - I hope there'll be some video of it taken.
Any kind of feedback or contribution is always welcome :+1:

The roadmap for the nearest future, is as follows:
**kRPC server v0.4.0** should be released soon :confetti_ball::smile:. Because `proto_change_0.4` branch is at the moment free from any major bugs (AFAIK), I decided that I'm going to release **krpc-rb v0.4.0** as soon as **kRPC server v0.4.0** is released. There are some features of **kRPC server v0.4.0** missing from `proto_change_0.4` branch at the moment (e.g. [#1][1], [#2][2]), and I probably won't have the time to implement them before **server v0.4.0** drops. I'm aiming to add those missing features in subsequent release(s) (possibly **krpc-rb v0.4.1**), but if anyone would provide a PR, i would be only happy to merge it.

[1]: https://github.com/TeWu/krpc-rb/issues/10
[2]: https://github.com/TeWu/krpc-rb/issues/14

**Comment by nateberkopec** [comment]
Woohoo! 🎉

**Comment by nateberkopec** [comment]
It looks like support for Events is incomplete because Expressions aren't supported - is that correct?

**Comment by nateberkopec** [comment]
No obvious bugs so far. Great release 👍

**Comment by TeWu** [comment]
Good to hear that. Thanks for feedback.

**Pull request merged**
